// Placement presets — a single dropdown maps to bannerType + page + position.
//
// Each entry corresponds to exactly one slot the storefront queries. Keep this
// in sync with the storefront components listed in `consumer`: if a slot has no
// banner, that section renders the shared placeholder (or hides itself).
//
// Shared by AddBanner and EditBanner — do not fork this list.
export const PLACEMENT_OPTIONS = [
  {
    value: "homepage_carousel",
    label: "Homepage Top Carousel",
    description: "Main hero slider at the top of the homepage. Add multiple images for carousel slides.",
    consumer: "Home/Navbar.jsx",
    bannerType: "header",
    page: "home",
    position: "top",
    showPerImageFields: true,
    showPromo: false,
    showButtonText: true,
    showSubheader: true,
    showBody: true,
  },
  {
    value: "homepage_hero",
    label: "Homepage Hero (Cleopatra Section)",
    description: "Large hero image with text overlay in the Cleopatra Glam section.",
    consumer: "Home/CleopatraGlam.jsx",
    bannerType: "hero",
    page: "home",
    position: "hero",
    showPerImageFields: false,
    showPromo: false,
    showButtonText: true,
    showSubheader: true,
    showBody: true,
  },
  {
    value: "homepage_promotional",
    label: "Homepage Promotional Card",
    description: "Small promo card below the hero section. Create 2 of these for the side-by-side layout.",
    consumer: "Home/CleopatraGlam.jsx",
    bannerType: "promotional",
    page: "home",
    position: "top",
    showPerImageFields: false,
    showPromo: true,
    showButtonText: true,
    showSubheader: true,
    showBody: false,
  },
  {
    value: "homepage_flash_sale",
    label: "Homepage Flash Sale",
    description: "Background banner for the Flash Sale section with countdown timer. Set an End Date for the timer.",
    consumer: "Home/FlashSale.jsx",
    bannerType: "slider",
    page: "home",
    position: "top",
    showPerImageFields: false,
    showPromo: false,
    showButtonText: false,
    showSubheader: false,
    showBody: true,
  },
  {
    value: "homepage_sidebar",
    label: "Homepage Sidebar (BestSeller Sale)",
    description: "Sale panel on the left side of the BestSeller section.",
    consumer: "Home/BestSeller.jsx",
    bannerType: "header",
    page: "home",
    position: "sidebar",
    showPerImageFields: false,
    showPromo: false,
    showButtonText: true,
    showSubheader: true,
    showBody: false,
  },
  {
    value: "homepage_middle",
    label: "Homepage Middle Banner",
    description: "Full-width banner between content sections on the homepage.",
    consumer: "Home/ExploreProducts.jsx",
    bannerType: "header",
    page: "home",
    position: "middle",
    showPerImageFields: false,
    showPromo: false,
    showButtonText: true,
    showSubheader: true,
    showBody: true,
  },
  {
    value: "homepage_bottom",
    label: "Homepage Pre-Footer Tiles",
    description: "Row of image tiles just above the footer. Add 4 images; each image's Title is used as its caption.",
    consumer: "Home/TopFooter.jsx",
    bannerType: "header",
    page: "home",
    position: "bottom",
    showPerImageFields: true,
    showPromo: false,
    showButtonText: false,
    showSubheader: true,
    showBody: false,
  },
  {
    value: "navbar_menu",
    label: "Navigation Menu Imagery",
    description:
      "Circular thumbnails in the category menu. The first image is the 'All Jewellery' tile; the rest fill in for any category without its own image (set those under Categories).",
    consumer: "Home/Navbar.jsx",
    bannerType: "header",
    page: "home",
    position: "menu",
    showPerImageFields: true,
    showPromo: false,
    showButtonText: false,
    showSubheader: false,
    showBody: false,
  },
  {
    value: "category_top",
    label: "Category Page — Top Banner",
    description: "Header banner across the top of the category listing page.",
    consumer: "Category/Category.jsx",
    bannerType: "header",
    page: "category",
    position: "top",
    showPerImageFields: false,
    showPromo: false,
    showButtonText: true,
    showSubheader: true,
    showBody: true,
  },
  {
    value: "category_bottom",
    label: "Category Page — Bottom Banner",
    description: "Banner at the foot of the category listing page.",
    consumer: "Category/Category.jsx",
    bannerType: "footer",
    page: "category",
    position: "bottom",
    showPerImageFields: false,
    showPromo: false,
    showButtonText: true,
    showSubheader: true,
    showBody: true,
  },
  {
    value: "category_slider",
    label: "Category Page — Logo Strip",
    description: "Scrolling strip of logos or badges on the category page. Add one image per logo.",
    consumer: "Category/SliderLogo.jsx",
    bannerType: "slider",
    page: "category",
    position: "middle",
    showPerImageFields: true,
    showPromo: false,
    showButtonText: false,
    showSubheader: false,
    showBody: false,
  },
  {
    value: "about_top",
    label: "About Page — Top Banner",
    description: "Full-bleed image near the top of the About page.",
    consumer: "Pages/About.jsx",
    bannerType: "header",
    page: "about",
    position: "top",
    showPerImageFields: false,
    showPromo: false,
    showButtonText: false,
    showSubheader: true,
    showBody: false,
  },
  {
    value: "about_bottom",
    label: "About Page — Bottom Banner",
    description: "Full-bleed image with overlay text at the foot of the About page.",
    consumer: "Pages/About.jsx",
    bannerType: "footer",
    page: "about",
    position: "bottom",
    showPerImageFields: false,
    showPromo: false,
    showButtonText: false,
    showSubheader: true,
    showBody: false,
  },
];

// Resolve a stored banner back to the preset it was created from.
export const findPlacement = (banner) =>
  PLACEMENT_OPTIONS.find(
    (option) =>
      option.page === banner?.page &&
      option.position === banner?.position &&
      option.bannerType === banner?.bannerType
  );

export default PLACEMENT_OPTIONS;
